wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      Bounding Box Debugger/Images_wandb_delimeter_predictions:
        key: Bounding Box Debugger/Images_wandb_delimeter_predictions
        type: bounding_box/class_labels
        value:
          '0': General trash
          '1': Paper
          '2': Paper pack
          '3': Metal
          '4': Glass
          '5': Plastic
          '6': Styrofoam
          '7': Plastic bag
          '8': Battery
          '9': Clothing
    cli_version: 0.12.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1634176985
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      - 13
      - 16
      4: 3.8.5
      5: 0.12.4
      8:
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 48
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: ''
data:
  desc: null
  value: ./data/coco.yaml
data_dict:
  desc: null
  value:
    names:
    - General trash
    - Paper
    - Paper pack
    - Metal
    - Glass
    - Plastic
    - Styrofoam
    - Plastic bag
    - Battery
    - Clothing
    nc: 10
    path: /opt/ml/detection/yolov5/dataset
    test: /opt/ml/detection/yolov5/dataset/images/test
    train: /opt/ml/detection/yolov5/dataset/images/train
    val: /opt/ml/detection/yolov5/dataset/images/val
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 2
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value: 0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 1024
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: yolov5x6_2
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
patience:
  desc: null
  value: 100
project:
  desc: null
  value: garbage_ObjectDetection
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: garbage_ObjectDetection/yolov5x6_225
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: yolov5s.pt
workers:
  desc: null
  value: 4
